/** @deprecated 请使用 anchor-attendance-status.util */
export {
  type AnchorAttendanceStatus,
  type AnchorAttendanceStatusPayload,
  type AnchorLateStatus,
  type AnchorLateStatusPayload,
  attachAnchorScheduleLateFields,
  buildActualLivePeriodText,
  calculateAnchorAttendanceStatus,
  calculateAnchorLateStatus,
  deriveSessionLabelFromSchedule,
  earliestSessionStart,
  formatDisplaySessionLabel,
  formatScheduleActualTimingLine,
  matchManualSchedule,
  pickEarliestValidSession,
  pickLatestValidSessionEnd,
  resolveAnchorAttendanceFromSessions,
  resolveAnchorLateStatusFromSessions,
  resolveFallbackSessionDisplay,
  resolveShopNameFromSchedule,
  toAttendanceStatusPayload,
  toLateStatusPayload,
} from './anchor-attendance-status.util'
